### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by margaritarr** [JackQChen/SoftwareLicense#1]
您好~
      请问软件授权端和客户端能提供一下使用教程吗~
谢谢~

**Comment by JackQChen** [comment]
一直没注意到这个Issue >_<<br>
我更新了一下README.md，里面有使用方式，可以获取下最新<br>
![image](https://user-images.githubusercontent.com/12838089/151565897-5304511b-f058-46fd-9ac3-3dcb745c17c7.png)
