### ISSUE TITLE
示例中使用了一组RSA密钥，实际项目中需要使用RSAKey生成新的密钥来使用

### ISSUE THREAD

**Issue by bwinzhb** [JackQChen/SoftwareLicense#2]
请问公私匙，怎样使用RSAKey生成？
本人新手还望不吝指教!
Thanks!

**Comment by JackQChen** [comment]
谦虚啦，我更新了一下README.md，里面有使用方式<br>
主要过程就是要生成一组新的密钥，替换到项目里面去用，可以获取下最新代码<br>
![image](https://user-images.githubusercontent.com/12838089/151565213-4e6f384b-0dd7-46a6-8271-0ba5b701d606.png)

**Comment by bwinzhb** [comment]
2.调用rsa.RSAKey方法后将生成一组密钥，私钥及对应的公钥，进行记录

没有看到哪里有调用rsa.RSAKey？
rsa.RSAKey需要两个参数。
