### ISSUE TITLE
貌似您的代码没有更新啊？

### ISSUE THREAD

**Issue by bwinzhb** [JackQChen/SoftwareLicense#3]
谦虚啦，我更新了一下README.md，里面有使用方式
主要过程就是要生成一组新的密钥，替换到项目里面去用，可以获取下最新代码
使用方式
1.取消注释Generator项目中FrmGenerate.cs第37、38行内容，在39行添加断点，运行Generator项目
2.调用rsa.RSAKey方法后将生成一组密钥，私钥及对应的公钥，进行记录
3.替换私钥到Generator项目中FrmGenerate.cs的privateKey内容
4.替换公钥到Register项目中Validate.cs的publicKey内容
5.可以使用Generator和Register对自己的项目(Client测试)添加授权验证了

貌似您的代码没有更新啊？

**Comment by JackQChen** [comment]
我检查了一下，是更新过的，你拉取下最新代码应该就可以了
555bbe9[](https://github.com/JackQChen/SoftwareLicense/commit/555bbe9a12051579bc82be2cec99ec6dfc541d44)

**Comment by bwinzhb** [comment]
大神你看看
SoftwareLicense/Generator/FrmGenerate.cs 
第37 38是这样的啊？
没有你说的
1.取消注释Generator项目中FrmGenerate.cs第37、38行内容
` private void FrmGenerate_Load(object sender, EventArgs e)
36        {
37            dateTimePicker1.Value = DateTime.Now;
38            saveFileDialog1.InitialDirectory = AppDomain.CurrentDomain.BaseDirectory;
39        }
`

**Comment by bwinzhb** [comment]
大佬你看看第37 38行没有你说的？

**Comment by JackQChen** [comment]
实在抱歉，光看是提交了，没有注意内容漏掉了，现在拉下最新应该有了

**Comment by bwinzhb** [comment]
感谢大佬，问题已经解决！
